using Demo.SR.PolyProject.API.Middlewares;
using Demo.SR.PolyProject.API.Utilitities;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System.IO;
using System.Runtime.CompilerServices;

namespace Demo.SR.PolyProject.API.Utilities
{
    public  class Trace
    {
        private readonly  ICorrelationIdAccessor _correlationIdAccessor;

         public Trace( ICorrelationIdAccessor correlationIdAccessor)
        {
            _correlationIdAccessor = correlationIdAccessor;
        }

        public static void TraceMessage( ILogger _logger, string message,
        [CallerMemberName] string memberName = "",
        [CallerFilePath] string sourceFilePath = "",
        [CallerLineNumber] int sourceLineNumber = 0)
        {
            
            //_logger.LogInformation($"{message} {memberName} {sourceFilePath}:{sourceLineNumber}");
            _logger.LogInformation($"Request generated by {memberName} from {Path.GetFileName(sourceFilePath)}:{sourceLineNumber} {message}");


        }

    }
}
